# Generated by Django 3.2.9 on 2021-11-25 02:49

from django.db import migrations


def give_admin_permissions(apps, schema):
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("users", "User")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    content_type = ContentType.objects.get_for_model(User)
    can_create_users = Permission.objects.create(
        codename="can_create_workers",
        name="Can Create Workers",
        content_type=content_type
    )
    admins = Group.objects.get(name="administrators")
    admins.permissions.add(can_create_users)


def delete_admin_permission(apps, schema):
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    admins = Group.objects.get(name="administrators")
    admins.permissions.delete()
    Permission.objects.get(codename="can_create_workers").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(give_admin_permissions, delete_admin_permission)
    ]
