# Generated by Django 3.2.9 on 2021-11-25 04:40

from django.db import migrations


def give_item_permissions(apps, schema):
    Group = apps.get_model("auth", "Group")
    Item = apps.get_model("items", "Item")
    ItemStockAudit = apps.get_model("items", "ItemStockAudit")
    TransactionAudit = apps.get_model("items", "TransactionAudit")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    content_type_item = ContentType.objects.get_for_model(Item)
    content_type_isa = ContentType.objects.get_for_model(ItemStockAudit)
    content_type_ta = ContentType.objects.get_for_model(TransactionAudit)
    can_admin_item = Permission.objects.create(
        codename="can_administer_item",
        name="Can Administer Item",
        content_type=content_type_item
    )
    can_log_stock = Permission.objects.create(
        codename="can_log_stock",
        name="Can Log Stock",
        content_type=content_type_isa
    )
    can_view_stats = Permission.objects.create(
        codename="can_view_stats",
        name="Can View Stats",
        content_type=content_type_ta
    )

    admins = Group.objects.get(name="administrators")
    admins.permissions.add(can_admin_item)
    admins.permissions.add(can_log_stock)
    admins.permissions.add(can_view_stats)

    workers = Group.objects.get(name="workers")
    workers.permissions.add(can_log_stock)


def delete_item_permission(apps, schema):
    Permission = apps.get_model("auth", "Permission")

    permissions = ["can_view_stats", "can_log_stock", "can_administer_item"]
    for permission in permissions:
        Permission.objects.get(codename=permission).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(give_item_permissions, delete_item_permission)
    ]
